image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build-module:
  stage: build
  script:
    - npm install
    - npm run publish
    - cp dist/module.json .
    - cp package/*.zip .

  artifacts:
    paths:
      - '*.zip'
      - 'module.json'
  only:
    refs:
      - develop
      - master
